name: Rosd

on:
    push:
        branches: [ hauptdrum ]
    pull_request:
        branches: [ hauptdrum ]

jobs:
    ic:
        env:
            RUST_BACKTRACE: 1
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust:
                    - stable
                    - nightly

        steps:
            - uses: actions/checkout@v3

            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true

            - name: Beispiele lona
              uses: actions-rs/cargo@v1
              with:
                  command: run
